name: CI Security Lab

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run App
        run: node app.js

      # 🔐 Secret Scan
      - name: Secret Scan
        run: |
          if grep -r "password" .; then
            echo "❌ Found secret"
            exit 1
          fi
